version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-ecom
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 628056@Hk
      MYSQL_DATABASE: ecomnew
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 628056@Hk
    ports:
      - "8082:80"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest



  e-commerce-app:
    image: hemantkumar6/e-commerce-app:latest
    container_name: e-commerce-app
    restart: always
    depends_on:
      - mysql
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecomnew?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 628056@Hk
      SPRING_JPA_HIBERNATE_DDL_AUTO: update


      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest




    ports:
      - "8081:8080"

volumes:
  mysql_data:
